### ISSUE TITLE
Failing to compile on FreeBSD 9.1

### ISSUE THREAD

**Issue by ehouse** [dannyn/slimlock#6]
g++  -Wall -I. -I/usr/local/include/freetype2  -D_THREAD_SAFE -I/usr/local/include   -pthread -DPACKAGE=\"slimlock\" -DVERSION=\"0.11\" -DPKGDATADIR=\"/usr/share/slim\" -DSYSCONFDIR=\"/etc\"  -c cfg.cpp -o cfg.o
g++  -Wall -I. -I/usr/local/include/freetype2  -D_THREAD_SAFE -I/usr/local/include   -pthread -DPACKAGE=\"slimlock\" -DVERSION=\"0.11\" -DPKGDATADIR=\"/usr/share/slim\" -DSYSCONFDIR=\"/etc\"  -c image.cpp -o image.o
g++  -Wall -I. -I/usr/local/include/freetype2  -D_THREAD_SAFE -I/usr/local/include   -pthread -DPACKAGE=\"slimlock\" -DVERSION=\"0.11\" -DPKGDATADIR=\"/usr/share/slim\" -DSYSCONFDIR=\"/etc\"  -c panel.cpp -o panel.o
panel.cpp: In constructor 'Panel::Panel(Display_, int, Window, Cfg_, const std::string&)':
panel.cpp:100: error: 'basename' was not declared in this scope
panel.cpp:117: error: 'basename' was not declared in this scope
gmake: **\* [panel.o] Error 1
